/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedPlanillasRouteRouteImport } from './routes/_authenticated/planillas/route'
import { Route as AuthenticatedInformeIndividualEstudianteRouteRouteImport } from './routes/_authenticated/informe-individual-estudiante/route'
import { Route as AuthenticatedInformeCualitativoRouteRouteImport } from './routes/_authenticated/informe-cualitativo/route'
import { Route as AuthenticatedGradebookRouteRouteImport } from './routes/_authenticated/gradebook/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGestionIndexRouteImport } from './routes/_authenticated/gestion/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAcademicSettingsIndexRouteImport } from './routes/_authenticated/academic-settings/index'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedGestionPonderadoRouteImport } from './routes/_authenticated/gestion/ponderado'
import { Route as AuthenticatedGestionColegiosRouteImport } from './routes/_authenticated/gestion/colegios'
import { Route as AuthenticatedGestionAlumnosRouteImport } from './routes/_authenticated/gestion/alumnos'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedAcademicSettingsSubjectsRouteImport } from './routes/_authenticated/academic-settings/subjects'
import { Route as AuthenticatedAcademicSettingsGradesRouteImport } from './routes/_authenticated/academic-settings/grades'
import { Route as AuthenticatedAcademicSettingsAssignmentsRouteImport } from './routes/_authenticated/academic-settings/assignments'
import { Route as AuthenticatedPlanillasTestRouteRouteImport } from './routes/_authenticated/planillas/test/route'
import { Route as AuthenticatedPlanillasSimpleTestRouteRouteImport } from './routes/_authenticated/planillas/simple-test/route'
import { Route as AuthenticatedGestionColegiosIndexRouteImport } from './routes/_authenticated/gestion/colegios/index'
import { Route as AuthenticatedPlanillasSubjectIdGradeIdRouteRouteImport } from './routes/_authenticated/planillas/$subjectId/$gradeId/route'
import { Route as AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRouteImport } from './routes/_authenticated/gestion/colegios/$colegioId/academic-settings/index'
import { Route as AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRouteImport } from './routes/_authenticated/gestion/colegios/$colegioId/academic-settings/weights'
import { Route as AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRouteImport } from './routes/_authenticated/gestion/colegios/$colegioId/academic-settings/subjects'
import { Route as AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRouteImport } from './routes/_authenticated/gestion/colegios/$colegioId/academic-settings/grades'
import { Route as AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRouteImport } from './routes/_authenticated/gestion/colegios/$colegioId/academic-settings/assignments'
import { Route as AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRouteImport } from './routes/_authenticated/gestion/colegios/$colegioId/academic-settings/alumnos'
import { Route as AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRouteImport } from './routes/_authenticated/gestion/colegios/$colegio/alumnosId/academic-settings'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanillasRouteRoute =
  AuthenticatedPlanillasRouteRouteImport.update({
    id: '/planillas',
    path: '/planillas',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformeIndividualEstudianteRouteRoute =
  AuthenticatedInformeIndividualEstudianteRouteRouteImport.update({
    id: '/informe-individual-estudiante',
    path: '/informe-individual-estudiante',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedInformeCualitativoRouteRoute =
  AuthenticatedInformeCualitativoRouteRouteImport.update({
    id: '/informe-cualitativo',
    path: '/informe-cualitativo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGradebookRouteRoute =
  AuthenticatedGradebookRouteRouteImport.update({
    id: '/gradebook',
    path: '/gradebook',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestionIndexRoute =
  AuthenticatedGestionIndexRouteImport.update({
    id: '/gestion/',
    path: '/gestion/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcademicSettingsIndexRoute =
  AuthenticatedAcademicSettingsIndexRouteImport.update({
    id: '/academic-settings/',
    path: '/academic-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedGestionPonderadoRoute =
  AuthenticatedGestionPonderadoRouteImport.update({
    id: '/gestion/ponderado',
    path: '/gestion/ponderado',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestionColegiosRoute =
  AuthenticatedGestionColegiosRouteImport.update({
    id: '/gestion/colegios',
    path: '/gestion/colegios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGestionAlumnosRoute =
  AuthenticatedGestionAlumnosRouteImport.update({
    id: '/gestion/alumnos',
    path: '/gestion/alumnos',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicSettingsSubjectsRoute =
  AuthenticatedAcademicSettingsSubjectsRouteImport.update({
    id: '/academic-settings/subjects',
    path: '/academic-settings/subjects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicSettingsGradesRoute =
  AuthenticatedAcademicSettingsGradesRouteImport.update({
    id: '/academic-settings/grades',
    path: '/academic-settings/grades',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcademicSettingsAssignmentsRoute =
  AuthenticatedAcademicSettingsAssignmentsRouteImport.update({
    id: '/academic-settings/assignments',
    path: '/academic-settings/assignments',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlanillasTestRouteRoute =
  AuthenticatedPlanillasTestRouteRouteImport.update({
    id: '/test',
    path: '/test',
    getParentRoute: () => AuthenticatedPlanillasRouteRoute,
  } as any)
const AuthenticatedPlanillasSimpleTestRouteRoute =
  AuthenticatedPlanillasSimpleTestRouteRouteImport.update({
    id: '/simple-test',
    path: '/simple-test',
    getParentRoute: () => AuthenticatedPlanillasRouteRoute,
  } as any)
const AuthenticatedGestionColegiosIndexRoute =
  AuthenticatedGestionColegiosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedGestionColegiosRoute,
  } as any)
const AuthenticatedPlanillasSubjectIdGradeIdRouteRoute =
  AuthenticatedPlanillasSubjectIdGradeIdRouteRouteImport.update({
    id: '/$subjectId/$gradeId',
    path: '/$subjectId/$gradeId',
    getParentRoute: () => AuthenticatedPlanillasRouteRoute,
  } as any)
const AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute =
  AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRouteImport.update({
    id: '/$colegioId/academic-settings/',
    path: '/$colegioId/academic-settings/',
    getParentRoute: () => AuthenticatedGestionColegiosRoute,
  } as any)
const AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute =
  AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRouteImport.update(
    {
      id: '/$colegioId/academic-settings/weights',
      path: '/$colegioId/academic-settings/weights',
      getParentRoute: () => AuthenticatedGestionColegiosRoute,
    } as any,
  )
const AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute =
  AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRouteImport.update(
    {
      id: '/$colegioId/academic-settings/subjects',
      path: '/$colegioId/academic-settings/subjects',
      getParentRoute: () => AuthenticatedGestionColegiosRoute,
    } as any,
  )
const AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute =
  AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRouteImport.update(
    {
      id: '/$colegioId/academic-settings/grades',
      path: '/$colegioId/academic-settings/grades',
      getParentRoute: () => AuthenticatedGestionColegiosRoute,
    } as any,
  )
const AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute =
  AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRouteImport.update(
    {
      id: '/$colegioId/academic-settings/assignments',
      path: '/$colegioId/academic-settings/assignments',
      getParentRoute: () => AuthenticatedGestionColegiosRoute,
    } as any,
  )
const AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute =
  AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRouteImport.update(
    {
      id: '/$colegioId/academic-settings/alumnos',
      path: '/$colegioId/academic-settings/alumnos',
      getParentRoute: () => AuthenticatedGestionColegiosRoute,
    } as any,
  )
const AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute =
  AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRouteImport.update(
    {
      id: '/$colegio/alumnosId/academic-settings',
      path: '/$colegio/alumnosId/academic-settings',
      getParentRoute: () => AuthenticatedGestionColegiosRoute,
    } as any,
  )

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/gradebook': typeof AuthenticatedGradebookRouteRoute
  '/informe-cualitativo': typeof AuthenticatedInformeCualitativoRouteRoute
  '/informe-individual-estudiante': typeof AuthenticatedInformeIndividualEstudianteRouteRoute
  '/planillas': typeof AuthenticatedPlanillasRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/planillas/simple-test': typeof AuthenticatedPlanillasSimpleTestRouteRoute
  '/planillas/test': typeof AuthenticatedPlanillasTestRouteRoute
  '/academic-settings/assignments': typeof AuthenticatedAcademicSettingsAssignmentsRoute
  '/academic-settings/grades': typeof AuthenticatedAcademicSettingsGradesRoute
  '/academic-settings/subjects': typeof AuthenticatedAcademicSettingsSubjectsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/gestion/alumnos': typeof AuthenticatedGestionAlumnosRoute
  '/gestion/colegios': typeof AuthenticatedGestionColegiosRouteWithChildren
  '/gestion/ponderado': typeof AuthenticatedGestionPonderadoRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/academic-settings/': typeof AuthenticatedAcademicSettingsIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/gestion/': typeof AuthenticatedGestionIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/teams/': typeof AuthenticatedTeamsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/planillas/$subjectId/$gradeId': typeof AuthenticatedPlanillasSubjectIdGradeIdRouteRoute
  '/gestion/colegios/': typeof AuthenticatedGestionColegiosIndexRoute
  '/gestion/colegios/$colegio/alumnosId/academic-settings': typeof AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute
  '/gestion/colegios/$colegioId/academic-settings/alumnos': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute
  '/gestion/colegios/$colegioId/academic-settings/assignments': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute
  '/gestion/colegios/$colegioId/academic-settings/grades': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute
  '/gestion/colegios/$colegioId/academic-settings/subjects': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute
  '/gestion/colegios/$colegioId/academic-settings/weights': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute
  '/gestion/colegios/$colegioId/academic-settings/': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/gradebook': typeof AuthenticatedGradebookRouteRoute
  '/informe-cualitativo': typeof AuthenticatedInformeCualitativoRouteRoute
  '/informe-individual-estudiante': typeof AuthenticatedInformeIndividualEstudianteRouteRoute
  '/planillas': typeof AuthenticatedPlanillasRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/planillas/simple-test': typeof AuthenticatedPlanillasSimpleTestRouteRoute
  '/planillas/test': typeof AuthenticatedPlanillasTestRouteRoute
  '/academic-settings/assignments': typeof AuthenticatedAcademicSettingsAssignmentsRoute
  '/academic-settings/grades': typeof AuthenticatedAcademicSettingsGradesRoute
  '/academic-settings/subjects': typeof AuthenticatedAcademicSettingsSubjectsRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/gestion/alumnos': typeof AuthenticatedGestionAlumnosRoute
  '/gestion/ponderado': typeof AuthenticatedGestionPonderadoRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/academic-settings': typeof AuthenticatedAcademicSettingsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/gestion': typeof AuthenticatedGestionIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/planillas/$subjectId/$gradeId': typeof AuthenticatedPlanillasSubjectIdGradeIdRouteRoute
  '/gestion/colegios': typeof AuthenticatedGestionColegiosIndexRoute
  '/gestion/colegios/$colegio/alumnosId/academic-settings': typeof AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute
  '/gestion/colegios/$colegioId/academic-settings/alumnos': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute
  '/gestion/colegios/$colegioId/academic-settings/assignments': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute
  '/gestion/colegios/$colegioId/academic-settings/grades': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute
  '/gestion/colegios/$colegioId/academic-settings/subjects': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute
  '/gestion/colegios/$colegioId/academic-settings/weights': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute
  '/gestion/colegios/$colegioId/academic-settings': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/gradebook': typeof AuthenticatedGradebookRouteRoute
  '/_authenticated/informe-cualitativo': typeof AuthenticatedInformeCualitativoRouteRoute
  '/_authenticated/informe-individual-estudiante': typeof AuthenticatedInformeIndividualEstudianteRouteRoute
  '/_authenticated/planillas': typeof AuthenticatedPlanillasRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/planillas/simple-test': typeof AuthenticatedPlanillasSimpleTestRouteRoute
  '/_authenticated/planillas/test': typeof AuthenticatedPlanillasTestRouteRoute
  '/_authenticated/academic-settings/assignments': typeof AuthenticatedAcademicSettingsAssignmentsRoute
  '/_authenticated/academic-settings/grades': typeof AuthenticatedAcademicSettingsGradesRoute
  '/_authenticated/academic-settings/subjects': typeof AuthenticatedAcademicSettingsSubjectsRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/gestion/alumnos': typeof AuthenticatedGestionAlumnosRoute
  '/_authenticated/gestion/colegios': typeof AuthenticatedGestionColegiosRouteWithChildren
  '/_authenticated/gestion/ponderado': typeof AuthenticatedGestionPonderadoRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/academic-settings/': typeof AuthenticatedAcademicSettingsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/gestion/': typeof AuthenticatedGestionIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/planillas/$subjectId/$gradeId': typeof AuthenticatedPlanillasSubjectIdGradeIdRouteRoute
  '/_authenticated/gestion/colegios/': typeof AuthenticatedGestionColegiosIndexRoute
  '/_authenticated/gestion/colegios/$colegio/alumnosId/academic-settings': typeof AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute
  '/_authenticated/gestion/colegios/$colegioId/academic-settings/alumnos': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute
  '/_authenticated/gestion/colegios/$colegioId/academic-settings/assignments': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute
  '/_authenticated/gestion/colegios/$colegioId/academic-settings/grades': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute
  '/_authenticated/gestion/colegios/$colegioId/academic-settings/subjects': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute
  '/_authenticated/gestion/colegios/$colegioId/academic-settings/weights': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute
  '/_authenticated/gestion/colegios/$colegioId/academic-settings/': typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gradebook'
    | '/informe-cualitativo'
    | '/informe-individual-estudiante'
    | '/planillas'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/planillas/simple-test'
    | '/planillas/test'
    | '/academic-settings/assignments'
    | '/academic-settings/grades'
    | '/academic-settings/subjects'
    | '/errors/$error'
    | '/gestion/alumnos'
    | '/gestion/colegios'
    | '/gestion/ponderado'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/academic-settings/'
    | '/apps/'
    | '/chats/'
    | '/gestion/'
    | '/help-center/'
    | '/settings/'
    | '/tasks/'
    | '/teams/'
    | '/users/'
    | '/planillas/$subjectId/$gradeId'
    | '/gestion/colegios/'
    | '/gestion/colegios/$colegio/alumnosId/academic-settings'
    | '/gestion/colegios/$colegioId/academic-settings/alumnos'
    | '/gestion/colegios/$colegioId/academic-settings/assignments'
    | '/gestion/colegios/$colegioId/academic-settings/grades'
    | '/gestion/colegios/$colegioId/academic-settings/subjects'
    | '/gestion/colegios/$colegioId/academic-settings/weights'
    | '/gestion/colegios/$colegioId/academic-settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/gradebook'
    | '/informe-cualitativo'
    | '/informe-individual-estudiante'
    | '/planillas'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/planillas/simple-test'
    | '/planillas/test'
    | '/academic-settings/assignments'
    | '/academic-settings/grades'
    | '/academic-settings/subjects'
    | '/errors/$error'
    | '/gestion/alumnos'
    | '/gestion/ponderado'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/academic-settings'
    | '/apps'
    | '/chats'
    | '/gestion'
    | '/help-center'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
    | '/planillas/$subjectId/$gradeId'
    | '/gestion/colegios'
    | '/gestion/colegios/$colegio/alumnosId/academic-settings'
    | '/gestion/colegios/$colegioId/academic-settings/alumnos'
    | '/gestion/colegios/$colegioId/academic-settings/assignments'
    | '/gestion/colegios/$colegioId/academic-settings/grades'
    | '/gestion/colegios/$colegioId/academic-settings/subjects'
    | '/gestion/colegios/$colegioId/academic-settings/weights'
    | '/gestion/colegios/$colegioId/academic-settings'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/gradebook'
    | '/_authenticated/informe-cualitativo'
    | '/_authenticated/informe-individual-estudiante'
    | '/_authenticated/planillas'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/planillas/simple-test'
    | '/_authenticated/planillas/test'
    | '/_authenticated/academic-settings/assignments'
    | '/_authenticated/academic-settings/grades'
    | '/_authenticated/academic-settings/subjects'
    | '/_authenticated/errors/$error'
    | '/_authenticated/gestion/alumnos'
    | '/_authenticated/gestion/colegios'
    | '/_authenticated/gestion/ponderado'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/academic-settings/'
    | '/_authenticated/apps/'
    | '/_authenticated/chats/'
    | '/_authenticated/gestion/'
    | '/_authenticated/help-center/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/teams/'
    | '/_authenticated/users/'
    | '/_authenticated/planillas/$subjectId/$gradeId'
    | '/_authenticated/gestion/colegios/'
    | '/_authenticated/gestion/colegios/$colegio/alumnosId/academic-settings'
    | '/_authenticated/gestion/colegios/$colegioId/academic-settings/alumnos'
    | '/_authenticated/gestion/colegios/$colegioId/academic-settings/assignments'
    | '/_authenticated/gestion/colegios/$colegioId/academic-settings/grades'
    | '/_authenticated/gestion/colegios/$colegioId/academic-settings/subjects'
    | '/_authenticated/gestion/colegios/$colegioId/academic-settings/weights'
    | '/_authenticated/gestion/colegios/$colegioId/academic-settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planillas': {
      id: '/_authenticated/planillas'
      path: '/planillas'
      fullPath: '/planillas'
      preLoaderRoute: typeof AuthenticatedPlanillasRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informe-individual-estudiante': {
      id: '/_authenticated/informe-individual-estudiante'
      path: '/informe-individual-estudiante'
      fullPath: '/informe-individual-estudiante'
      preLoaderRoute: typeof AuthenticatedInformeIndividualEstudianteRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informe-cualitativo': {
      id: '/_authenticated/informe-cualitativo'
      path: '/informe-cualitativo'
      fullPath: '/informe-cualitativo'
      preLoaderRoute: typeof AuthenticatedInformeCualitativoRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gradebook': {
      id: '/_authenticated/gradebook'
      path: '/gradebook'
      fullPath: '/gradebook'
      preLoaderRoute: typeof AuthenticatedGradebookRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams/'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestion/': {
      id: '/_authenticated/gestion/'
      path: '/gestion'
      fullPath: '/gestion/'
      preLoaderRoute: typeof AuthenticatedGestionIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-settings/': {
      id: '/_authenticated/academic-settings/'
      path: '/academic-settings'
      fullPath: '/academic-settings/'
      preLoaderRoute: typeof AuthenticatedAcademicSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/gestion/ponderado': {
      id: '/_authenticated/gestion/ponderado'
      path: '/gestion/ponderado'
      fullPath: '/gestion/ponderado'
      preLoaderRoute: typeof AuthenticatedGestionPonderadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestion/colegios': {
      id: '/_authenticated/gestion/colegios'
      path: '/gestion/colegios'
      fullPath: '/gestion/colegios'
      preLoaderRoute: typeof AuthenticatedGestionColegiosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gestion/alumnos': {
      id: '/_authenticated/gestion/alumnos'
      path: '/gestion/alumnos'
      fullPath: '/gestion/alumnos'
      preLoaderRoute: typeof AuthenticatedGestionAlumnosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-settings/subjects': {
      id: '/_authenticated/academic-settings/subjects'
      path: '/academic-settings/subjects'
      fullPath: '/academic-settings/subjects'
      preLoaderRoute: typeof AuthenticatedAcademicSettingsSubjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-settings/grades': {
      id: '/_authenticated/academic-settings/grades'
      path: '/academic-settings/grades'
      fullPath: '/academic-settings/grades'
      preLoaderRoute: typeof AuthenticatedAcademicSettingsGradesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/academic-settings/assignments': {
      id: '/_authenticated/academic-settings/assignments'
      path: '/academic-settings/assignments'
      fullPath: '/academic-settings/assignments'
      preLoaderRoute: typeof AuthenticatedAcademicSettingsAssignmentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/planillas/test': {
      id: '/_authenticated/planillas/test'
      path: '/test'
      fullPath: '/planillas/test'
      preLoaderRoute: typeof AuthenticatedPlanillasTestRouteRouteImport
      parentRoute: typeof AuthenticatedPlanillasRouteRoute
    }
    '/_authenticated/planillas/simple-test': {
      id: '/_authenticated/planillas/simple-test'
      path: '/simple-test'
      fullPath: '/planillas/simple-test'
      preLoaderRoute: typeof AuthenticatedPlanillasSimpleTestRouteRouteImport
      parentRoute: typeof AuthenticatedPlanillasRouteRoute
    }
    '/_authenticated/gestion/colegios/': {
      id: '/_authenticated/gestion/colegios/'
      path: '/'
      fullPath: '/gestion/colegios/'
      preLoaderRoute: typeof AuthenticatedGestionColegiosIndexRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/planillas/$subjectId/$gradeId': {
      id: '/_authenticated/planillas/$subjectId/$gradeId'
      path: '/$subjectId/$gradeId'
      fullPath: '/planillas/$subjectId/$gradeId'
      preLoaderRoute: typeof AuthenticatedPlanillasSubjectIdGradeIdRouteRouteImport
      parentRoute: typeof AuthenticatedPlanillasRouteRoute
    }
    '/_authenticated/gestion/colegios/$colegioId/academic-settings/': {
      id: '/_authenticated/gestion/colegios/$colegioId/academic-settings/'
      path: '/$colegioId/academic-settings'
      fullPath: '/gestion/colegios/$colegioId/academic-settings/'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/gestion/colegios/$colegioId/academic-settings/weights': {
      id: '/_authenticated/gestion/colegios/$colegioId/academic-settings/weights'
      path: '/$colegioId/academic-settings/weights'
      fullPath: '/gestion/colegios/$colegioId/academic-settings/weights'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/gestion/colegios/$colegioId/academic-settings/subjects': {
      id: '/_authenticated/gestion/colegios/$colegioId/academic-settings/subjects'
      path: '/$colegioId/academic-settings/subjects'
      fullPath: '/gestion/colegios/$colegioId/academic-settings/subjects'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/gestion/colegios/$colegioId/academic-settings/grades': {
      id: '/_authenticated/gestion/colegios/$colegioId/academic-settings/grades'
      path: '/$colegioId/academic-settings/grades'
      fullPath: '/gestion/colegios/$colegioId/academic-settings/grades'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/gestion/colegios/$colegioId/academic-settings/assignments': {
      id: '/_authenticated/gestion/colegios/$colegioId/academic-settings/assignments'
      path: '/$colegioId/academic-settings/assignments'
      fullPath: '/gestion/colegios/$colegioId/academic-settings/assignments'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/gestion/colegios/$colegioId/academic-settings/alumnos': {
      id: '/_authenticated/gestion/colegios/$colegioId/academic-settings/alumnos'
      path: '/$colegioId/academic-settings/alumnos'
      fullPath: '/gestion/colegios/$colegioId/academic-settings/alumnos'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
    '/_authenticated/gestion/colegios/$colegio/alumnosId/academic-settings': {
      id: '/_authenticated/gestion/colegios/$colegio/alumnosId/academic-settings'
      path: '/$colegio/alumnosId/academic-settings'
      fullPath: '/gestion/colegios/$colegio/alumnosId/academic-settings'
      preLoaderRoute: typeof AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRouteImport
      parentRoute: typeof AuthenticatedGestionColegiosRoute
    }
  }
}

interface AuthenticatedPlanillasRouteRouteChildren {
  AuthenticatedPlanillasSimpleTestRouteRoute: typeof AuthenticatedPlanillasSimpleTestRouteRoute
  AuthenticatedPlanillasTestRouteRoute: typeof AuthenticatedPlanillasTestRouteRoute
  AuthenticatedPlanillasSubjectIdGradeIdRouteRoute: typeof AuthenticatedPlanillasSubjectIdGradeIdRouteRoute
}

const AuthenticatedPlanillasRouteRouteChildren: AuthenticatedPlanillasRouteRouteChildren =
  {
    AuthenticatedPlanillasSimpleTestRouteRoute:
      AuthenticatedPlanillasSimpleTestRouteRoute,
    AuthenticatedPlanillasTestRouteRoute: AuthenticatedPlanillasTestRouteRoute,
    AuthenticatedPlanillasSubjectIdGradeIdRouteRoute:
      AuthenticatedPlanillasSubjectIdGradeIdRouteRoute,
  }

const AuthenticatedPlanillasRouteRouteWithChildren =
  AuthenticatedPlanillasRouteRoute._addFileChildren(
    AuthenticatedPlanillasRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedGestionColegiosRouteChildren {
  AuthenticatedGestionColegiosIndexRoute: typeof AuthenticatedGestionColegiosIndexRoute
  AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute: typeof AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute
  AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute
  AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute
  AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute
  AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute
  AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute
  AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute: typeof AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute
}

const AuthenticatedGestionColegiosRouteChildren: AuthenticatedGestionColegiosRouteChildren =
  {
    AuthenticatedGestionColegiosIndexRoute:
      AuthenticatedGestionColegiosIndexRoute,
    AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute:
      AuthenticatedGestionColegiosColegioAlumnosIdAcademicSettingsRoute,
    AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute:
      AuthenticatedGestionColegiosColegioIdAcademicSettingsAlumnosRoute,
    AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute:
      AuthenticatedGestionColegiosColegioIdAcademicSettingsAssignmentsRoute,
    AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute:
      AuthenticatedGestionColegiosColegioIdAcademicSettingsGradesRoute,
    AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute:
      AuthenticatedGestionColegiosColegioIdAcademicSettingsSubjectsRoute,
    AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute:
      AuthenticatedGestionColegiosColegioIdAcademicSettingsWeightsRoute,
    AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute:
      AuthenticatedGestionColegiosColegioIdAcademicSettingsIndexRoute,
  }

const AuthenticatedGestionColegiosRouteWithChildren =
  AuthenticatedGestionColegiosRoute._addFileChildren(
    AuthenticatedGestionColegiosRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedGradebookRouteRoute: typeof AuthenticatedGradebookRouteRoute
  AuthenticatedInformeCualitativoRouteRoute: typeof AuthenticatedInformeCualitativoRouteRoute
  AuthenticatedInformeIndividualEstudianteRouteRoute: typeof AuthenticatedInformeIndividualEstudianteRouteRoute
  AuthenticatedPlanillasRouteRoute: typeof AuthenticatedPlanillasRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAcademicSettingsAssignmentsRoute: typeof AuthenticatedAcademicSettingsAssignmentsRoute
  AuthenticatedAcademicSettingsGradesRoute: typeof AuthenticatedAcademicSettingsGradesRoute
  AuthenticatedAcademicSettingsSubjectsRoute: typeof AuthenticatedAcademicSettingsSubjectsRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGestionAlumnosRoute: typeof AuthenticatedGestionAlumnosRoute
  AuthenticatedGestionColegiosRoute: typeof AuthenticatedGestionColegiosRouteWithChildren
  AuthenticatedGestionPonderadoRoute: typeof AuthenticatedGestionPonderadoRoute
  AuthenticatedAcademicSettingsIndexRoute: typeof AuthenticatedAcademicSettingsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedGestionIndexRoute: typeof AuthenticatedGestionIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedGradebookRouteRoute: AuthenticatedGradebookRouteRoute,
  AuthenticatedInformeCualitativoRouteRoute:
    AuthenticatedInformeCualitativoRouteRoute,
  AuthenticatedInformeIndividualEstudianteRouteRoute:
    AuthenticatedInformeIndividualEstudianteRouteRoute,
  AuthenticatedPlanillasRouteRoute:
    AuthenticatedPlanillasRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAcademicSettingsAssignmentsRoute:
    AuthenticatedAcademicSettingsAssignmentsRoute,
  AuthenticatedAcademicSettingsGradesRoute:
    AuthenticatedAcademicSettingsGradesRoute,
  AuthenticatedAcademicSettingsSubjectsRoute:
    AuthenticatedAcademicSettingsSubjectsRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGestionAlumnosRoute: AuthenticatedGestionAlumnosRoute,
  AuthenticatedGestionColegiosRoute:
    AuthenticatedGestionColegiosRouteWithChildren,
  AuthenticatedGestionPonderadoRoute: AuthenticatedGestionPonderadoRoute,
  AuthenticatedAcademicSettingsIndexRoute:
    AuthenticatedAcademicSettingsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedGestionIndexRoute: AuthenticatedGestionIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
